### ISSUE TITLE
Donate Page

### ISSUE THREAD

**Issue by anastasialanz** [silverli/FairPlay#6]
# DONATE 
FAIR:PLAY is just one of the efforts led by the Women’s Law Project to achieve gender equity in Pennsylvania and across the country. 
We invite you to support (DIRECT TO DONATE PAGE OF WLP SITE) the Women’s Law Project in high-impact litigation, legislative action, and advocacy to advance gender equity. 
 

Facebook 
Twitter

**Comment by acosby** [comment]
![4 donate](https://cloud.githubusercontent.com/assets/12141357/22863452/25254fce-f10e-11e6-8b51-53e6afc9d64f.png)
