### ISSUE TITLE
Home Page

### ISSUE THREAD

**Issue by anastasialanz** [silverli/FairPlay#7]
**Pennsylvania schools are short changing female athletes.** 
Title IX guarantees equitable educational opportunities for girls and young women, including in athletics. The law has been in force for over 40 years, yet many Pennsylvania schools do not appear to be complying. 
**Is your school one of them?** 
Find your school’s Title IX gap and see how it compares to other schools in your county and statewide.

FIND MY SCHOOL
COMPARE MY SCHOOL
TAKE ACTION
DONATE

**Comment by acosby** [comment]
obviously missing some links, but thinking the search functionality would be best on the homepage

![welcome](https://cloud.githubusercontent.com/assets/12141357/22854688/49ff1338-f042-11e6-8111-c142bc850707.png)

**Comment by acosby** [comment]
![1 welcome copy 4](https://cloud.githubusercontent.com/assets/12141357/22863599/2e34ebd0-f111-11e6-99f5-444318169490.png)
